/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_services_tenant = pgEnum("enum_services_tenant", [
  "beclean",
  "bejob",
]);
export const enum_products_category = pgEnum("enum_products_category", [
  "chemicals",
  "hygiene",
  "tools",
  "paper",
  "industrial",
]);
export const enum_products_tenant = pgEnum("enum_products_tenant", [
  "beclean",
  "bejob",
]);
export const enum_blog_posts_category = pgEnum("enum_blog_posts_category", [
  "Conseils Bureaux",
  "Réglementation",
  "Chantier & BTP",
  "Résidentiel",
  "Hygiène",
]);
export const enum_blog_posts_tenant = pgEnum("enum_blog_posts_tenant", [
  "beclean",
  "bejob",
]);
export const enum_testimonials_tenant = pgEnum("enum_testimonials_tenant", [
  "beclean",
  "bejob",
]);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const services_features = pgTable(
  "services_features",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    text: varchar("text").notNull(),
  },
  (columns) => [
    index("services_features_order_idx").on(columns._order),
    index("services_features_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [services.id],
      name: "services_features_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const services = pgTable(
  "services",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    shortDesc: varchar("short_desc").notNull(),
    description: jsonb("description"),
    icon: varchar("icon").notNull(),
    baseRate: numeric("base_rate", { mode: "number" }),
    tenant: enum_services_tenant("tenant").notNull().default("beclean"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("services_slug_idx").on(columns.slug),
    index("services_updated_at_idx").on(columns.updatedAt),
    index("services_created_at_idx").on(columns.createdAt),
  ],
);

export const products_features = pgTable(
  "products_features",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    text: varchar("text").notNull(),
  },
  (columns) => [
    index("products_features_order_idx").on(columns._order),
    index("products_features_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [products.id],
      name: "products_features_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const products = pgTable(
  "products",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    category: enum_products_category("category").notNull(),
    categoryLabel: varchar("category_label").notNull(),
    price: numeric("price", { mode: "number" }).notNull(),
    unit: varchar("unit").notNull(),
    description: jsonb("description"),
    rating: numeric("rating", { mode: "number" }).default(4.5),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    tenant: enum_products_tenant("tenant").notNull().default("beclean"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("products_slug_idx").on(columns.slug),
    index("products_image_idx").on(columns.image),
    index("products_updated_at_idx").on(columns.updatedAt),
    index("products_created_at_idx").on(columns.createdAt),
  ],
);

export const blog_posts = pgTable(
  "blog_posts",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    excerpt: varchar("excerpt").notNull(),
    content: jsonb("content").notNull(),
    category: enum_blog_posts_category("category").notNull(),
    readTime: varchar("read_time").notNull(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    tenant: enum_blog_posts_tenant("tenant").notNull().default("beclean"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("blog_posts_slug_idx").on(columns.slug),
    index("blog_posts_image_idx").on(columns.image),
    index("blog_posts_updated_at_idx").on(columns.updatedAt),
    index("blog_posts_created_at_idx").on(columns.createdAt),
  ],
);

export const testimonials = pgTable(
  "testimonials",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    role: varchar("role").notNull(),
    content: varchar("content").notNull(),
    stars: numeric("stars", { mode: "number" }).notNull().default(5),
    tenant: enum_testimonials_tenant("tenant").notNull().default("beclean"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("testimonials_updated_at_idx").on(columns.updatedAt),
    index("testimonials_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    servicesID: integer("services_id"),
    productsID: integer("products_id"),
    "blog-postsID": integer("blog_posts_id"),
    testimonialsID: integer("testimonials_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_services_id_idx").on(
      columns.servicesID,
    ),
    index("payload_locked_documents_rels_products_id_idx").on(
      columns.productsID,
    ),
    index("payload_locked_documents_rels_blog_posts_id_idx").on(
      columns["blog-postsID"],
    ),
    index("payload_locked_documents_rels_testimonials_id_idx").on(
      columns.testimonialsID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["servicesID"]],
      foreignColumns: [services.id],
      name: "payload_locked_documents_rels_services_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["productsID"]],
      foreignColumns: [products.id],
      name: "payload_locked_documents_rels_products_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["blog-postsID"]],
      foreignColumns: [blog_posts.id],
      name: "payload_locked_documents_rels_blog_posts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["testimonialsID"]],
      foreignColumns: [testimonials.id],
      name: "payload_locked_documents_rels_testimonials_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const site_settings = pgTable("site_settings", {
  id: serial("id").primaryKey(),
  companyName: varchar("company_name").notNull().default("BeClean"),
  legalName: varchar("legal_name").default(
    "BeClean Filiale BeFacility S.A.R.L.",
  ),
  tagline: varchar("tagline").default(
    "Le partenaire propreté complet au Maroc : Services, Produits & Matériel",
  ),
  phone: varchar("phone").default("+212 520 90 09 00"),
  whatsapp: varchar("whatsapp").default("+212 663 10 08 40"),
  email: varchar("email").default("contact@befacility.com"),
  supportEmail: varchar("support_email").default("support@befacility.com"),
  address: varchar("address").default("Belvedere, Casablanca, Maroc"),
  ice: varchar("ice").default("003954092000044"),
  socials_linkedin: varchar("socials_linkedin").default(
    "https://linkedin.com/company/beclean-maroc",
  ),
  socials_facebook: varchar("socials_facebook").default(
    "https://facebook.com/beclean.ma",
  ),
  socials_instagram: varchar("socials_instagram").default(
    "https://instagram.com/beclean.ma",
  ),
  socials_tiktok: varchar("socials_tiktok").default(
    "https://tiktok.com/@beclean.ma",
  ),
  socials_youtube: varchar("socials_youtube").default(
    "https://youtube.com/@beclean.ma",
  ),
  socials_twitter: varchar("socials_twitter").default(
    "https://x.com/beclean_ma",
  ),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const home_page_stats = pgTable(
  "home_page_stats",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    number: varchar("number").notNull(),
    label: varchar("label").notNull(),
  },
  (columns) => [
    index("home_page_stats_order_idx").on(columns._order),
    index("home_page_stats_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home_page.id],
      name: "home_page_stats_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const home_page = pgTable("home_page", {
  id: serial("id").primaryKey(),
  hero_title: varchar("hero_title")
    .notNull()
    .default("Votre Partenaire Propreté Complet au Maroc"),
  hero_subtitle: varchar("hero_subtitle").default(
    "Protocoles de désinfection certifiés et nettoyage éco-responsable pour vos bureaux et locaux",
  ),
  about_title: varchar("about_title").default(
    "L'Excellence au Service de Vos Locaux",
  ),
  about_description: varchar("about_description").default(
    "Fondée à Casablanca, BeClean est rapidement devenue une référence du nettoyage B2B et résidentiel haut de gamme. Nous allions l'utilisation de technologies modernes (auto-laveuses silencieuses, détergents enzymatiques) avec une formation rigoureuse de nos agents.",
  ),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_services_features = relations(
  services_features,
  ({ one }) => ({
    _parentID: one(services, {
      fields: [services_features._parentID],
      references: [services.id],
      relationName: "features",
    }),
  }),
);
export const relations_services = relations(services, ({ many }) => ({
  features: many(services_features, {
    relationName: "features",
  }),
}));
export const relations_products_features = relations(
  products_features,
  ({ one }) => ({
    _parentID: one(products, {
      fields: [products_features._parentID],
      references: [products.id],
      relationName: "features",
    }),
  }),
);
export const relations_products = relations(products, ({ one, many }) => ({
  features: many(products_features, {
    relationName: "features",
  }),
  image: one(media, {
    fields: [products.image],
    references: [media.id],
    relationName: "image",
  }),
}));
export const relations_blog_posts = relations(blog_posts, ({ one }) => ({
  image: one(media, {
    fields: [blog_posts.image],
    references: [media.id],
    relationName: "image",
  }),
}));
export const relations_testimonials = relations(testimonials, () => ({}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    servicesID: one(services, {
      fields: [payload_locked_documents_rels.servicesID],
      references: [services.id],
      relationName: "services",
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: "products",
    }),
    "blog-postsID": one(blog_posts, {
      fields: [payload_locked_documents_rels["blog-postsID"]],
      references: [blog_posts.id],
      relationName: "blog-posts",
    }),
    testimonialsID: one(testimonials, {
      fields: [payload_locked_documents_rels.testimonialsID],
      references: [testimonials.id],
      relationName: "testimonials",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_site_settings = relations(site_settings, () => ({}));
export const relations_home_page_stats = relations(
  home_page_stats,
  ({ one }) => ({
    _parentID: one(home_page, {
      fields: [home_page_stats._parentID],
      references: [home_page.id],
      relationName: "stats",
    }),
  }),
);
export const relations_home_page = relations(home_page, ({ many }) => ({
  stats: many(home_page_stats, {
    relationName: "stats",
  }),
}));

type DatabaseSchema = {
  enum_services_tenant: typeof enum_services_tenant;
  enum_products_category: typeof enum_products_category;
  enum_products_tenant: typeof enum_products_tenant;
  enum_blog_posts_category: typeof enum_blog_posts_category;
  enum_blog_posts_tenant: typeof enum_blog_posts_tenant;
  enum_testimonials_tenant: typeof enum_testimonials_tenant;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  services_features: typeof services_features;
  services: typeof services;
  products_features: typeof products_features;
  products: typeof products;
  blog_posts: typeof blog_posts;
  testimonials: typeof testimonials;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  site_settings: typeof site_settings;
  home_page_stats: typeof home_page_stats;
  home_page: typeof home_page;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_services_features: typeof relations_services_features;
  relations_services: typeof relations_services;
  relations_products_features: typeof relations_products_features;
  relations_products: typeof relations_products;
  relations_blog_posts: typeof relations_blog_posts;
  relations_testimonials: typeof relations_testimonials;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_site_settings: typeof relations_site_settings;
  relations_home_page_stats: typeof relations_home_page_stats;
  relations_home_page: typeof relations_home_page;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
